server:
  servlet:
    tomcat:
      max-part-count: 20
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
    encoding:
      charset: utf-8
      force: true
  port: 8080

upload:
  root-dir: ./uploads/
  counselor-dir: counselor-images/
  member-dir: member-images/
  chat-dir: chat-images/
  record-image-dir: records/images/
  record-audio-dir: records/audio/
  record-video-dir: records/videos/
  community-dir: community-images/

logging:
  level:
    root: INFO
    com.take: DEBUG

spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: tb.mailSender423@gmail.com
    password: dpfmgohpiuhhmevc
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  mustache:
    suffix: .mustache
    prefix: classpath:/templates/
    cache: false
    charset: UTF-8
    servlet:
      expose-session-attributes: true
      expose-request-attributes: true

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/take_breath?useSSL=false&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: root
    password: asd1234

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 10
    defer-datasource-initialization: true

jwt:
  secret: ${JWT_SECRET}
  validityInMilliseconds: 3600000
  refresh-expiration-ms: 604800000

iamport:
  imp-code: ${IAMPORT_IMP_CODE}
  api-key: ${IAMPORT_API_KEY}
  api-secret: ${IAMPORT_API_SECRET}

youtube:
  api-key: ${YOUTUBE_API_KEY}
  base-url: https://www.googleapis.com/youtube/v3

naver:
  request-token-uri: https://nid.naver.com/oauth2.0/token
  client-id: ${NAVER_CLIENT_ID}
  client-secret: ${NAVER_CLIENT_SECRET}
