server:
  servlet:
    tomcat:
      max-part-count: 20 # ???? ?? input ??? ??? ??
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
    encoding:
      charset: utf-8
      force: true
  port: 8080

# ??? ?? ? ?? ?? ??
upload:
  root-dir: ./uploads/
  chat-dir: chat-images/
  chat-file-dir: chat-file/

# ?? ??? ??
# ERROR > WARN > INFO > DEBUG > TRACE
logging:
  level:
    root: INFO  # ?? ?????? INFO ??? ??
    com.tenco: DEBUG # ? ????? DEBUG ?? ?? ??

# spring ?? ??
spring:
  mustache:
    # ??? ??? ???? .mustache? ???? Mustache
    # ??? ??? ????? ??
    suffix: .mustache
    # ??? ??? ???
    # ?? ??? src/main/resources/templates/? ??
    prefix: classpath:/templates/
    # ?? ? ??? ??? ?????? ??
    # ?? ? ?? ????? ? (??????? true? ?? ??)
    cache: false
    # ??? ??? UTF-8 ????? ???? ?? ? ??? ?? ??
    charset: UTF-8
    servlet:
      # ??? ?? ??? ????? ?? ???? ?
      expose-session-attributes: true
      expose-request-attributes: true
  # ??? ??? ?? ?? (H2 ???? ??????)
  datasource:
    url: jdbc:h2:mem:testdb;MODE=MySQL;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true # ?? ??? ??


  # JPA ??
  jpa:
    hibernate:
      # create: ?????? ??? ???? ?? ??
      # ?? ???? ?? ??? (???)
      ddl-auto: create
    # SQL ??? ??? ?? (??? ???)
    show-sql: false
    properties:
      hibernate:
        # SQL ??? ?? ?? ???
        format_sql: true
        # in query ??
        default_batch_fetch_size: 10
    # data.sql ??? Hibernate ??? ??? ??
    defer-datasource-initialization: true
