server:
  servlet:
    tomcat:
      max-part-count: 20 # ???? ?? input ??? ??? ??
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
    encoding:
      charset: utf-8
      force: true
  port: 8080

# ??? ?? ? ?? ?? ??
upload:
  root-dir: ./uploads/
  corp-dir: corp-images/
  member-dir: member-images/
  chat-image-dir: chat-image/

# ?? ??? ??
# ERROR > WARN > INFO > DEBUG > TRACE
logging:
  level:
    root: INFO  # ?? ?????? INFO ??? ??
    com.take: DEBUG # ? ????? DEBUG ?? ?? ??

# 이미지 메세지 저장 경로
file:
  upload:
    path: C:/Users/GGG/Pictures/chat/images

# spring ?? ??
spring:
  mustache:
    # ??? ??? ???? .mustache? ???? Mustache
    # ??? ??? ????? ??
    suffix: .mustache
    # ??? ??? ???
    # ?? ??? src/main/resources/templates/? ??
    prefix: classpath:/templates/
    # ?? ? ??? ??? ?????? ??
    # ?? ? ?? ????? ? (??????? true? ?? ??)
    cache: false
    # ??? ??? UTF-8 ????? ???? ?? ? ??? ?? ??
    charset: UTF-8
    servlet:
      # ??? ?? ??? ????? ?? ???? ?
      expose-session-attributes: true
      expose-request-attributes: true
  # ??? ??? ?? ?? (H2 ???? ??????)
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/take_breath?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
    username: root
    password: asd1234

  # JPA ??
  jpa:
    hibernate:
      # create: ?????? ??? ???? ?? ??
      # ?? ???? ?? ??? (???)
      ddl-auto: create-drop
    # SQL ??? ??? ?? (??? ???)
    show-sql: true
    properties:
      hibernate:
        # SQL ??? ?? ?? ???
        format_sql: true
        # in query ??
        default_batch_fetch_size: 10
    # data.sql ??? Hibernate ??? ??? ??
    defer-datasource-initialization: true

# ----- !!
  mail:
    host: smtp.gmail.com
    port: 587
    username: your_email@gmail.com
    password: your_app_password   # Gmail은 앱 비밀번호 필요
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

jwt:
  secret: 'VGhpc0lzQVNlY3JldEtleUZvckpXVFNhZmUhIT8xMjM0NTY='
  expiration-in-ms: 3600000 # 1시간
